services:
  - type: web
    name: pharmacy-management
    env: python
    buildCommand: chmod +x deploy.sh && ./deploy.sh
    startCommand: gunicorn wsgi:app --log-level debug
    python_version: 3.11.11
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /auth/login 